//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBasket
    {
        public int BasketId { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Discount { get; set; }
    }
}
